### PR TITLE
Reward Pilot with a Positive Sound

### PR DESCRIPTION
**Pull request by pospispa**
I believe that every pilot at coding dojo does its best. IMHO, ending his session with a negative sound that says something like "get out of here" may be a discouraging experience.

That's why I propose to replace the current alarm.wav sound with a positive sound, i.e. an applause: https://www.freesoundeffects.com/free-track/applause7-426812/

### CODE REVIEW

**Comment by rhcarvalho** [comment]
While I seem to never have noticed "negativity" aspects, I'm favorable to improving the experience to something encouraging, or at least having the ability to choose.

In terms of implementation, what are the trade-offs of using an embedded sound resource vs. a .wav file?

@pospispa I think we need a license to use that sound? https://www.freesoundeffects.com/faq.php#3

**Comment by juanplopes** [comment]
I agree. Never thought this way, but it makes perfect sense. I'll accept it as soon as I get home, because those resource files are auto-generated by Visual Studio and editing them outside it usually gets me into trouble after some time.

Thanks for the contribution! :)

**Comment by rhcarvalho** [comment]
What we have noticed in the last 2 dojos is that this specific applause sound is too long, it takes some time before we can type the names of who was coding and continue.

**Comment by pospispa** [comment]
@rhcarvalho I found another applause sound with public domain licence so that we can use it. In addition, I shortened the sound to approx. 1 sec. that should be short enough.

Regarding the embedded sound resource vs. a .wav file. IMHO, it's easier to work with a .wav file. The embedded sound resources were introduced in [this commit](https://github.com/juanplopes/dojotimer/commit/9d142dfb6c05d8e9a609b1ba127a497880773070) in order to avoid a mono bug. Hopefully, the bug is already fixed.

**Comment by juanplopes** [comment]
Sorry for the delay accepting the PR. I just forgot :(

I'm wondering why I used PlaySync to play those files. Using regular Play method would allow the form to be shown while the sound is being played (allowing longer versions). I'm afraid there is something to do with Mono idiosyncrasies. As I'll be unable to test it properly, I'll leave it like that for now.

**Comment by rhcarvalho** [comment]
Thanks @juanplopes, we'll try the new version today :)

**Pull request merged**
